// Mocks generated by Mockito 5.3.2 from annotations
// in stackduo/test/services/coins/manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i16;
import 'dart:typed_data' as _i21;

import 'package:bip32/bip32.dart' as _i11;
import 'package:bip47/bip47.dart' as _i13;
import 'package:bitcoindart/bitcoindart.dart' as _i8;
import 'package:decimal/decimal.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:stackduo/db/main_db.dart' as _i7;
import 'package:stackduo/electrumx_rpc/cached_electrumx.dart' as _i5;
import 'package:stackduo/electrumx_rpc/electrumx.dart' as _i4;
import 'package:stackduo/models/balance.dart' as _i6;
import 'package:stackduo/models/isar/models/isar_models.dart' as _i12;
import 'package:stackduo/models/paymint/fee_object_model.dart' as _i3;
import 'package:stackduo/models/signing_data.dart' as _i19;
import 'package:stackduo/services/coins/bitcoin/bitcoin_wallet.dart' as _i15;
import 'package:stackduo/services/transaction_notification_tracker.dart' as _i2;
import 'package:stackduo/utilities/amount/amount.dart' as _i9;
import 'package:stackduo/utilities/enums/coin_enum.dart' as _i17;
import 'package:stackduo/utilities/enums/derive_path_type_enum.dart' as _i18;
import 'package:stackduo/utilities/flutter_secure_storage_interface.dart'
    as _i20;
import 'package:tuple/tuple.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTransactionNotificationTracker_0 extends _i1.SmartFake
    implements _i2.TransactionNotificationTracker {
  _FakeTransactionNotificationTracker_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFeeObject_1 extends _i1.SmartFake implements _i3.FeeObject {
  _FakeFeeObject_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeElectrumX_2 extends _i1.SmartFake implements _i4.ElectrumX {
  _FakeElectrumX_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCachedElectrumX_3 extends _i1.SmartFake
    implements _i5.CachedElectrumX {
  _FakeCachedElectrumX_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBalance_4 extends _i1.SmartFake implements _i6.Balance {
  _FakeBalance_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMainDB_5 extends _i1.SmartFake implements _i7.MainDB {
  _FakeMainDB_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNetworkType_6 extends _i1.SmartFake implements _i8.NetworkType {
  _FakeNetworkType_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeElectrumXNode_7 extends _i1.SmartFake implements _i4.ElectrumXNode {
  _FakeElectrumXNode_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAmount_8 extends _i1.SmartFake implements _i9.Amount {
  _FakeAmount_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTuple2_9<T1, T2> extends _i1.SmartFake
    implements _i10.Tuple2<T1, T2> {
  _FakeTuple2_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBIP32_10 extends _i1.SmartFake implements _i11.BIP32 {
  _FakeBIP32_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAddress_11 extends _i1.SmartFake implements _i12.Address {
  _FakeAddress_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentCode_12 extends _i1.SmartFake implements _i13.PaymentCode {
  _FakePaymentCode_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDecimal_13 extends _i1.SmartFake implements _i14.Decimal {
  _FakeDecimal_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BitcoinWallet].
///
/// See the documentation for Mockito's code generation for more information.
class MockBitcoinWallet extends _i1.Mock implements _i15.BitcoinWallet {
  MockBitcoinWallet() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set timer(_i16.Timer? _timer) => super.noSuchMethod(
        Invocation.setter(
          #timer,
          _timer,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i2.TransactionNotificationTracker get txTracker => (super.noSuchMethod(
        Invocation.getter(#txTracker),
        returnValue: _FakeTransactionNotificationTracker_0(
          this,
          Invocation.getter(#txTracker),
        ),
      ) as _i2.TransactionNotificationTracker);
  @override
  set txTracker(_i2.TransactionNotificationTracker? _txTracker) =>
      super.noSuchMethod(
        Invocation.setter(
          #txTracker,
          _txTracker,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get longMutex => (super.noSuchMethod(
        Invocation.getter(#longMutex),
        returnValue: false,
      ) as bool);
  @override
  set longMutex(bool? _longMutex) => super.noSuchMethod(
        Invocation.setter(
          #longMutex,
          _longMutex,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get refreshMutex => (super.noSuchMethod(
        Invocation.getter(#refreshMutex),
        returnValue: false,
      ) as bool);
  @override
  set refreshMutex(bool? _refreshMutex) => super.noSuchMethod(
        Invocation.setter(
          #refreshMutex,
          _refreshMutex,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get isActive => (super.noSuchMethod(
        Invocation.getter(#isActive),
        returnValue: false,
      ) as bool);
  @override
  set isActive(bool? _isActive) => super.noSuchMethod(
        Invocation.setter(
          #isActive,
          _isActive,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set isFavorite(bool? markFavorite) => super.noSuchMethod(
        Invocation.setter(
          #isFavorite,
          markFavorite,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get isFavorite => (super.noSuchMethod(
        Invocation.getter(#isFavorite),
        returnValue: false,
      ) as bool);
  @override
  _i17.Coin get coin => (super.noSuchMethod(
        Invocation.getter(#coin),
        returnValue: _i17.Coin.bitcoin,
      ) as _i17.Coin);
  @override
  _i16.Future<List<_i12.UTXO>> get utxos => (super.noSuchMethod(
        Invocation.getter(#utxos),
        returnValue: _i16.Future<List<_i12.UTXO>>.value(<_i12.UTXO>[]),
      ) as _i16.Future<List<_i12.UTXO>>);
  @override
  _i16.Future<List<_i12.Transaction>> get transactions => (super.noSuchMethod(
        Invocation.getter(#transactions),
        returnValue:
            _i16.Future<List<_i12.Transaction>>.value(<_i12.Transaction>[]),
      ) as _i16.Future<List<_i12.Transaction>>);
  @override
  _i16.Future<String> get currentReceivingAddress => (super.noSuchMethod(
        Invocation.getter(#currentReceivingAddress),
        returnValue: _i16.Future<String>.value(''),
      ) as _i16.Future<String>);
  @override
  _i16.Future<String> get currentChangeAddress => (super.noSuchMethod(
        Invocation.getter(#currentChangeAddress),
        returnValue: _i16.Future<String>.value(''),
      ) as _i16.Future<String>);
  @override
  _i16.Future<String> get currentChangeAddressP2PKH => (super.noSuchMethod(
        Invocation.getter(#currentChangeAddressP2PKH),
        returnValue: _i16.Future<String>.value(''),
      ) as _i16.Future<String>);
  @override
  bool get hasCalledExit => (super.noSuchMethod(
        Invocation.getter(#hasCalledExit),
        returnValue: false,
      ) as bool);
  @override
  _i16.Future<_i3.FeeObject> get fees => (super.noSuchMethod(
        Invocation.getter(#fees),
        returnValue: _i16.Future<_i3.FeeObject>.value(_FakeFeeObject_1(
          this,
          Invocation.getter(#fees),
        )),
      ) as _i16.Future<_i3.FeeObject>);
  @override
  _i16.Future<int> get maxFee => (super.noSuchMethod(
        Invocation.getter(#maxFee),
        returnValue: _i16.Future<int>.value(0),
      ) as _i16.Future<int>);
  @override
  _i16.Future<List<String>> get mnemonic => (super.noSuchMethod(
        Invocation.getter(#mnemonic),
        returnValue: _i16.Future<List<String>>.value(<String>[]),
      ) as _i16.Future<List<String>>);
  @override
  _i16.Future<String?> get mnemonicString => (super.noSuchMethod(
        Invocation.getter(#mnemonicString),
        returnValue: _i16.Future<String?>.value(),
      ) as _i16.Future<String?>);
  @override
  _i16.Future<String?> get mnemonicPassphrase => (super.noSuchMethod(
        Invocation.getter(#mnemonicPassphrase),
        returnValue: _i16.Future<String?>.value(),
      ) as _i16.Future<String?>);
  @override
  _i16.Future<int> get chainHeight => (super.noSuchMethod(
        Invocation.getter(#chainHeight),
        returnValue: _i16.Future<int>.value(0),
      ) as _i16.Future<int>);
  @override
  int get storedChainHeight => (super.noSuchMethod(
        Invocation.getter(#storedChainHeight),
        returnValue: 0,
      ) as int);
  @override
  bool get shouldAutoSync => (super.noSuchMethod(
        Invocation.getter(#shouldAutoSync),
        returnValue: false,
      ) as bool);
  @override
  set shouldAutoSync(bool? shouldAutoSync) => super.noSuchMethod(
        Invocation.setter(
          #shouldAutoSync,
          shouldAutoSync,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get isRefreshing => (super.noSuchMethod(
        Invocation.getter(#isRefreshing),
        returnValue: false,
      ) as bool);
  @override
  bool get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: false,
      ) as bool);
  @override
  String get walletId => (super.noSuchMethod(
        Invocation.getter(#walletId),
        returnValue: '',
      ) as String);
  @override
  String get walletName => (super.noSuchMethod(
        Invocation.getter(#walletName),
        returnValue: '',
      ) as String);
  @override
  set walletName(String? newName) => super.noSuchMethod(
        Invocation.setter(
          #walletName,
          newName,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i4.ElectrumX get electrumXClient => (super.noSuchMethod(
        Invocation.getter(#electrumXClient),
        returnValue: _FakeElectrumX_2(
          this,
          Invocation.getter(#electrumXClient),
        ),
      ) as _i4.ElectrumX);
  @override
  _i5.CachedElectrumX get cachedElectrumXClient => (super.noSuchMethod(
        Invocation.getter(#cachedElectrumXClient),
        returnValue: _FakeCachedElectrumX_3(
          this,
          Invocation.getter(#cachedElectrumXClient),
        ),
      ) as _i5.CachedElectrumX);
  @override
  _i6.Balance get balance => (super.noSuchMethod(
        Invocation.getter(#balance),
        returnValue: _FakeBalance_4(
          this,
          Invocation.getter(#balance),
        ),
      ) as _i6.Balance);
  @override
  _i16.Future<String> get xpub => (super.noSuchMethod(
        Invocation.getter(#xpub),
        returnValue: _i16.Future<String>.value(''),
      ) as _i16.Future<String>);
  @override
  set onIsActiveWalletChanged(void Function(bool)? _onIsActiveWalletChanged) =>
      super.noSuchMethod(
        Invocation.setter(
          #onIsActiveWalletChanged,
          _onIsActiveWalletChanged,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i7.MainDB get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeMainDB_5(
          this,
          Invocation.getter(#db),
        ),
      ) as _i7.MainDB);
  @override
  _i8.NetworkType get networkType => (super.noSuchMethod(
        Invocation.getter(#networkType),
        returnValue: _FakeNetworkType_6(
          this,
          Invocation.getter(#networkType),
        ),
      ) as _i8.NetworkType);
  @override
  _i16.Future<void> exit() => (super.noSuchMethod(
        Invocation.method(
          #exit,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  _i18.DerivePathType addressType({required String? address}) =>
      (super.noSuchMethod(
        Invocation.method(
          #addressType,
          [],
          {#address: address},
        ),
        returnValue: _i18.DerivePathType.bip44,
      ) as _i18.DerivePathType);
  @override
  _i16.Future<void> recoverFromMnemonic({
    required String? mnemonic,
    String? mnemonicPassphrase,
    required int? maxUnusedAddressGap,
    required int? maxNumberOfIndexesToCheck,
    required int? height,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #recoverFromMnemonic,
          [],
          {
            #mnemonic: mnemonic,
            #mnemonicPassphrase: mnemonicPassphrase,
            #maxUnusedAddressGap: maxUnusedAddressGap,
            #maxNumberOfIndexesToCheck: maxNumberOfIndexesToCheck,
            #height: height,
          },
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  _i16.Future<void> getTransactionCacheEarly(List<String>? allAddresses) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactionCacheEarly,
          [allAddresses],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  _i16.Future<bool> refreshIfThereIsNewData() => (super.noSuchMethod(
        Invocation.method(
          #refreshIfThereIsNewData,
          [],
        ),
        returnValue: _i16.Future<bool>.value(false),
      ) as _i16.Future<bool>);
  @override
  _i16.Future<void> getAllTxsToWatch() => (super.noSuchMethod(
        Invocation.method(
          #getAllTxsToWatch,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  _i16.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  _i16.Future<Map<String, dynamic>> prepareSend({
    required String? address,
    required _i9.Amount? amount,
    Map<String, dynamic>? args,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #prepareSend,
          [],
          {
            #address: address,
            #amount: amount,
            #args: args,
          },
        ),
        returnValue:
            _i16.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i16.Future<Map<String, dynamic>>);
  @override
  _i16.Future<String> confirmSend({required Map<String, dynamic>? txData}) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmSend,
          [],
          {#txData: txData},
        ),
        returnValue: _i16.Future<String>.value(''),
      ) as _i16.Future<String>);
  @override
  _i16.Future<bool> testNetworkConnection() => (super.noSuchMethod(
        Invocation.method(
          #testNetworkConnection,
          [],
        ),
        returnValue: _i16.Future<bool>.value(false),
      ) as _i16.Future<bool>);
  @override
  void startNetworkAlivePinging() => super.noSuchMethod(
        Invocation.method(
          #startNetworkAlivePinging,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void stopNetworkAlivePinging() => super.noSuchMethod(
        Invocation.method(
          #stopNetworkAlivePinging,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i16.Future<void> initializeNew() => (super.noSuchMethod(
        Invocation.method(
          #initializeNew,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  _i16.Future<void> initializeExisting() => (super.noSuchMethod(
        Invocation.method(
          #initializeExisting,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  _i16.Future<void> updateSentCachedTxData(Map<String, dynamic>? txData) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSentCachedTxData,
          [txData],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  bool validateAddress(String? address) => (super.noSuchMethod(
        Invocation.method(
          #validateAddress,
          [address],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i16.Future<void> updateNode(bool? shouldRefresh) => (super.noSuchMethod(
        Invocation.method(
          #updateNode,
          [shouldRefresh],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  _i16.Future<_i4.ElectrumXNode> getCurrentNode() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentNode,
          [],
        ),
        returnValue: _i16.Future<_i4.ElectrumXNode>.value(_FakeElectrumXNode_7(
          this,
          Invocation.method(
            #getCurrentNode,
            [],
          ),
        )),
      ) as _i16.Future<_i4.ElectrumXNode>);
  @override
  _i16.Future<List<Map<String, dynamic>>> fastFetch(
          List<String>? allTxHashes) =>
      (super.noSuchMethod(
        Invocation.method(
          #fastFetch,
          [allTxHashes],
        ),
        returnValue: _i16.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i16.Future<List<Map<String, dynamic>>>);
  @override
  _i16.Future<int> getTxCount({required String? address}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTxCount,
          [],
          {#address: address},
        ),
        returnValue: _i16.Future<int>.value(0),
      ) as _i16.Future<int>);
  @override
  _i16.Future<void> checkCurrentReceivingAddressesForTransactions() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkCurrentReceivingAddressesForTransactions,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  _i16.Future<void> checkCurrentChangeAddressesForTransactions() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkCurrentChangeAddressesForTransactions,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  int estimateTxFee({
    required int? vSize,
    required int? feeRatePerKB,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #estimateTxFee,
          [],
          {
            #vSize: vSize,
            #feeRatePerKB: feeRatePerKB,
          },
        ),
        returnValue: 0,
      ) as int);
  @override
  dynamic coinSelection({
    required int? satoshiAmountToSend,
    required int? selectedTxFeeRate,
    required String? recipientAddress,
    required bool? coinControl,
    required bool? isSendAll,
    int? additionalOutputs = 0,
    List<_i12.UTXO>? utxos,
  }) =>
      super.noSuchMethod(Invocation.method(
        #coinSelection,
        [],
        {
          #satoshiAmountToSend: satoshiAmountToSend,
          #selectedTxFeeRate: selectedTxFeeRate,
          #recipientAddress: recipientAddress,
          #coinControl: coinControl,
          #isSendAll: isSendAll,
          #additionalOutputs: additionalOutputs,
          #utxos: utxos,
        },
      ));
  @override
  _i16.Future<List<_i19.SigningData>> fetchBuildTxData(
          List<_i12.UTXO>? utxosToUse) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchBuildTxData,
          [utxosToUse],
        ),
        returnValue:
            _i16.Future<List<_i19.SigningData>>.value(<_i19.SigningData>[]),
      ) as _i16.Future<List<_i19.SigningData>>);
  @override
  _i16.Future<Map<String, dynamic>> buildTransaction({
    required List<_i19.SigningData>? utxoSigningData,
    required List<String>? recipients,
    required List<int>? satoshiAmounts,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #buildTransaction,
          [],
          {
            #utxoSigningData: utxoSigningData,
            #recipients: recipients,
            #satoshiAmounts: satoshiAmounts,
          },
        ),
        returnValue:
            _i16.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i16.Future<Map<String, dynamic>>);
  @override
  _i16.Future<void> fullRescan(
    int? maxUnusedAddressGap,
    int? maxNumberOfIndexesToCheck,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fullRescan,
          [
            maxUnusedAddressGap,
            maxNumberOfIndexesToCheck,
          ],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  _i16.Future<_i9.Amount> estimateFeeFor(
    _i9.Amount? amount,
    int? feeRate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #estimateFeeFor,
          [
            amount,
            feeRate,
          ],
        ),
        returnValue: _i16.Future<_i9.Amount>.value(_FakeAmount_8(
          this,
          Invocation.method(
            #estimateFeeFor,
            [
              amount,
              feeRate,
            ],
          ),
        )),
      ) as _i16.Future<_i9.Amount>);
  @override
  _i9.Amount roughFeeEstimate(
    int? inputCount,
    int? outputCount,
    int? feeRatePerKB,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #roughFeeEstimate,
          [
            inputCount,
            outputCount,
            feeRatePerKB,
          ],
        ),
        returnValue: _FakeAmount_8(
          this,
          Invocation.method(
            #roughFeeEstimate,
            [
              inputCount,
              outputCount,
              feeRatePerKB,
            ],
          ),
        ),
      ) as _i9.Amount);
  @override
  _i16.Future<_i9.Amount> sweepAllEstimate(int? feeRate) => (super.noSuchMethod(
        Invocation.method(
          #sweepAllEstimate,
          [feeRate],
        ),
        returnValue: _i16.Future<_i9.Amount>.value(_FakeAmount_8(
          this,
          Invocation.method(
            #sweepAllEstimate,
            [feeRate],
          ),
        )),
      ) as _i16.Future<_i9.Amount>);
  @override
  _i16.Future<bool> generateNewAddress() => (super.noSuchMethod(
        Invocation.method(
          #generateNewAddress,
          [],
        ),
        returnValue: _i16.Future<bool>.value(false),
      ) as _i16.Future<bool>);
  @override
  void initCache(
    String? walletId,
    _i17.Coin? coin,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #initCache,
          [
            walletId,
            coin,
          ],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i16.Future<void> updateCachedId(String? id) => (super.noSuchMethod(
        Invocation.method(
          #updateCachedId,
          [id],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  int getCachedChainHeight() => (super.noSuchMethod(
        Invocation.method(
          #getCachedChainHeight,
          [],
        ),
        returnValue: 0,
      ) as int);
  @override
  _i16.Future<void> updateCachedChainHeight(int? height) => (super.noSuchMethod(
        Invocation.method(
          #updateCachedChainHeight,
          [height],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  bool getCachedIsFavorite() => (super.noSuchMethod(
        Invocation.method(
          #getCachedIsFavorite,
          [],
        ),
        returnValue: false,
      ) as bool);
  @override
  _i16.Future<void> updateCachedIsFavorite(bool? isFavorite) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCachedIsFavorite,
          [isFavorite],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  _i6.Balance getCachedBalance() => (super.noSuchMethod(
        Invocation.method(
          #getCachedBalance,
          [],
        ),
        returnValue: _FakeBalance_4(
          this,
          Invocation.method(
            #getCachedBalance,
            [],
          ),
        ),
      ) as _i6.Balance);
  @override
  _i16.Future<void> updateCachedBalance(_i6.Balance? balance) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCachedBalance,
          [balance],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  _i6.Balance getCachedBalanceSecondary() => (super.noSuchMethod(
        Invocation.method(
          #getCachedBalanceSecondary,
          [],
        ),
        returnValue: _FakeBalance_4(
          this,
          Invocation.method(
            #getCachedBalanceSecondary,
            [],
          ),
        ),
      ) as _i6.Balance);
  @override
  _i16.Future<void> updateCachedBalanceSecondary(_i6.Balance? balance) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCachedBalanceSecondary,
          [balance],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  void initWalletDB({_i7.MainDB? mockableOverride}) => super.noSuchMethod(
        Invocation.method(
          #initWalletDB,
          [],
          {#mockableOverride: mockableOverride},
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i16.Future<_i10.Tuple2<_i12.Transaction, _i12.Address>> parseTransaction(
    Map<String, dynamic>? txData,
    dynamic electrumxClient,
    List<_i12.Address>? myAddresses,
    _i17.Coin? coin,
    int? minConfirms,
    String? walletId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #parseTransaction,
          [
            txData,
            electrumxClient,
            myAddresses,
            coin,
            minConfirms,
            walletId,
          ],
        ),
        returnValue:
            _i16.Future<_i10.Tuple2<_i12.Transaction, _i12.Address>>.value(
                _FakeTuple2_9<_i12.Transaction, _i12.Address>(
          this,
          Invocation.method(
            #parseTransaction,
            [
              txData,
              electrumxClient,
              myAddresses,
              coin,
              minConfirms,
              walletId,
            ],
          ),
        )),
      ) as _i16.Future<_i10.Tuple2<_i12.Transaction, _i12.Address>>);
  @override
  void initPaynymWalletInterface({
    required String? walletId,
    required String? walletName,
    required _i8.NetworkType? network,
    required _i17.Coin? coin,
    required _i7.MainDB? db,
    required _i4.ElectrumX? electrumXClient,
    required _i20.SecureStorageInterface? secureStorage,
    required int? dustLimit,
    required int? dustLimitP2PKH,
    required int? minConfirms,
    required _i16.Future<String?> Function()? getMnemonicString,
    required _i16.Future<String?> Function()? getMnemonicPassphrase,
    required _i16.Future<int> Function()? getChainHeight,
    required _i16.Future<String> Function()? getCurrentChangeAddress,
    required int Function({
      required int feeRatePerKB,
      required int vSize,
    })?
        estimateTxFee,
    required _i16.Future<Map<String, dynamic>> Function({
      required String address,
      required _i9.Amount amount,
      Map<String, dynamic>? args,
    })?
        prepareSend,
    required _i16.Future<int> Function({required String address})? getTxCount,
    required _i16.Future<List<_i19.SigningData>> Function(List<_i12.UTXO>)?
        fetchBuildTxData,
    required _i16.Future<void> Function()? refresh,
    required _i16.Future<void> Function()? checkChangeAddressForTransactions,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #initPaynymWalletInterface,
          [],
          {
            #walletId: walletId,
            #walletName: walletName,
            #network: network,
            #coin: coin,
            #db: db,
            #electrumXClient: electrumXClient,
            #secureStorage: secureStorage,
            #dustLimit: dustLimit,
            #dustLimitP2PKH: dustLimitP2PKH,
            #minConfirms: minConfirms,
            #getMnemonicString: getMnemonicString,
            #getMnemonicPassphrase: getMnemonicPassphrase,
            #getChainHeight: getChainHeight,
            #getCurrentChangeAddress: getCurrentChangeAddress,
            #estimateTxFee: estimateTxFee,
            #prepareSend: prepareSend,
            #getTxCount: getTxCount,
            #fetchBuildTxData: fetchBuildTxData,
            #refresh: refresh,
            #checkChangeAddressForTransactions:
                checkChangeAddressForTransactions,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i16.Future<_i11.BIP32> getBip47BaseNode() => (super.noSuchMethod(
        Invocation.method(
          #getBip47BaseNode,
          [],
        ),
        returnValue: _i16.Future<_i11.BIP32>.value(_FakeBIP32_10(
          this,
          Invocation.method(
            #getBip47BaseNode,
            [],
          ),
        )),
      ) as _i16.Future<_i11.BIP32>);
  @override
  _i16.Future<_i21.Uint8List> getPrivateKeyForPaynymReceivingAddress({
    required String? paymentCodeString,
    required int? index,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPrivateKeyForPaynymReceivingAddress,
          [],
          {
            #paymentCodeString: paymentCodeString,
            #index: index,
          },
        ),
        returnValue: _i16.Future<_i21.Uint8List>.value(_i21.Uint8List(0)),
      ) as _i16.Future<_i21.Uint8List>);
  @override
  _i16.Future<_i12.Address> currentReceivingPaynymAddress({
    required _i13.PaymentCode? sender,
    required bool? isSegwit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #currentReceivingPaynymAddress,
          [],
          {
            #sender: sender,
            #isSegwit: isSegwit,
          },
        ),
        returnValue: _i16.Future<_i12.Address>.value(_FakeAddress_11(
          this,
          Invocation.method(
            #currentReceivingPaynymAddress,
            [],
            {
              #sender: sender,
              #isSegwit: isSegwit,
            },
          ),
        )),
      ) as _i16.Future<_i12.Address>);
  @override
  _i16.Future<void> checkCurrentPaynymReceivingAddressForTransactions({
    required _i13.PaymentCode? sender,
    required bool? isSegwit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkCurrentPaynymReceivingAddressForTransactions,
          [],
          {
            #sender: sender,
            #isSegwit: isSegwit,
          },
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  _i16.Future<void> checkAllCurrentReceivingPaynymAddressesForTransactions() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkAllCurrentReceivingPaynymAddressesForTransactions,
          [],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  _i16.Future<_i11.BIP32> deriveNotificationBip32Node() => (super.noSuchMethod(
        Invocation.method(
          #deriveNotificationBip32Node,
          [],
        ),
        returnValue: _i16.Future<_i11.BIP32>.value(_FakeBIP32_10(
          this,
          Invocation.method(
            #deriveNotificationBip32Node,
            [],
          ),
        )),
      ) as _i16.Future<_i11.BIP32>);
  @override
  _i16.Future<_i13.PaymentCode> getPaymentCode({required bool? isSegwit}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentCode,
          [],
          {#isSegwit: isSegwit},
        ),
        returnValue: _i16.Future<_i13.PaymentCode>.value(_FakePaymentCode_12(
          this,
          Invocation.method(
            #getPaymentCode,
            [],
            {#isSegwit: isSegwit},
          ),
        )),
      ) as _i16.Future<_i13.PaymentCode>);
  @override
  _i16.Future<_i21.Uint8List> signWithNotificationKey(_i21.Uint8List? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #signWithNotificationKey,
          [data],
        ),
        returnValue: _i16.Future<_i21.Uint8List>.value(_i21.Uint8List(0)),
      ) as _i16.Future<_i21.Uint8List>);
  @override
  _i16.Future<String> signStringWithNotificationKey(String? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #signStringWithNotificationKey,
          [data],
        ),
        returnValue: _i16.Future<String>.value(''),
      ) as _i16.Future<String>);
  @override
  _i16.Future<Map<String, dynamic>> preparePaymentCodeSend({
    required _i13.PaymentCode? paymentCode,
    required bool? isSegwit,
    required _i9.Amount? amount,
    Map<String, dynamic>? args,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #preparePaymentCodeSend,
          [],
          {
            #paymentCode: paymentCode,
            #isSegwit: isSegwit,
            #amount: amount,
            #args: args,
          },
        ),
        returnValue:
            _i16.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i16.Future<Map<String, dynamic>>);
  @override
  _i16.Future<_i12.Address> nextUnusedSendAddressFrom({
    required _i13.PaymentCode? pCode,
    required bool? isSegwit,
    required _i11.BIP32? privateKeyNode,
    int? startIndex = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #nextUnusedSendAddressFrom,
          [],
          {
            #pCode: pCode,
            #isSegwit: isSegwit,
            #privateKeyNode: privateKeyNode,
            #startIndex: startIndex,
          },
        ),
        returnValue: _i16.Future<_i12.Address>.value(_FakeAddress_11(
          this,
          Invocation.method(
            #nextUnusedSendAddressFrom,
            [],
            {
              #pCode: pCode,
              #isSegwit: isSegwit,
              #privateKeyNode: privateKeyNode,
              #startIndex: startIndex,
            },
          ),
        )),
      ) as _i16.Future<_i12.Address>);
  @override
  _i16.Future<Map<String, dynamic>> prepareNotificationTx({
    required int? selectedTxFeeRate,
    required String? targetPaymentCodeString,
    int? additionalOutputs = 0,
    List<_i12.UTXO>? utxos,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #prepareNotificationTx,
          [],
          {
            #selectedTxFeeRate: selectedTxFeeRate,
            #targetPaymentCodeString: targetPaymentCodeString,
            #additionalOutputs: additionalOutputs,
            #utxos: utxos,
          },
        ),
        returnValue:
            _i16.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i16.Future<Map<String, dynamic>>);
  @override
  _i16.Future<String> broadcastNotificationTx(
          {required Map<String, dynamic>? preparedTx}) =>
      (super.noSuchMethod(
        Invocation.method(
          #broadcastNotificationTx,
          [],
          {#preparedTx: preparedTx},
        ),
        returnValue: _i16.Future<String>.value(''),
      ) as _i16.Future<String>);
  @override
  _i16.Future<bool> hasConnected(String? paymentCodeString) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasConnected,
          [paymentCodeString],
        ),
        returnValue: _i16.Future<bool>.value(false),
      ) as _i16.Future<bool>);
  @override
  _i16.Future<_i13.PaymentCode?> unBlindedPaymentCodeFromTransaction(
          {required _i12.Transaction? transaction}) =>
      (super.noSuchMethod(
        Invocation.method(
          #unBlindedPaymentCodeFromTransaction,
          [],
          {#transaction: transaction},
        ),
        returnValue: _i16.Future<_i13.PaymentCode?>.value(),
      ) as _i16.Future<_i13.PaymentCode?>);
  @override
  _i16.Future<_i13.PaymentCode?> unBlindedPaymentCodeFromTransactionBad(
          {required _i12.Transaction? transaction}) =>
      (super.noSuchMethod(
        Invocation.method(
          #unBlindedPaymentCodeFromTransactionBad,
          [],
          {#transaction: transaction},
        ),
        returnValue: _i16.Future<_i13.PaymentCode?>.value(),
      ) as _i16.Future<_i13.PaymentCode?>);
  @override
  _i16.Future<List<_i13.PaymentCode>>
      getAllPaymentCodesFromNotificationTransactions() => (super.noSuchMethod(
            Invocation.method(
              #getAllPaymentCodesFromNotificationTransactions,
              [],
            ),
            returnValue:
                _i16.Future<List<_i13.PaymentCode>>.value(<_i13.PaymentCode>[]),
          ) as _i16.Future<List<_i13.PaymentCode>>);
  @override
  _i16.Future<void> checkForNotificationTransactionsTo(
          Set<String>? otherCodeStrings) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkForNotificationTransactionsTo,
          [otherCodeStrings],
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  _i16.Future<void> restoreAllHistory({
    required int? maxUnusedAddressGap,
    required int? maxNumberOfIndexesToCheck,
    required Set<String>? paymentCodeStrings,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #restoreAllHistory,
          [],
          {
            #maxUnusedAddressGap: maxUnusedAddressGap,
            #maxNumberOfIndexesToCheck: maxNumberOfIndexesToCheck,
            #paymentCodeStrings: paymentCodeStrings,
          },
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  _i16.Future<void> restoreHistoryWith({
    required _i13.PaymentCode? other,
    required bool? checkSegwitAsWell,
    required int? maxUnusedAddressGap,
    required int? maxNumberOfIndexesToCheck,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #restoreHistoryWith,
          [],
          {
            #other: other,
            #checkSegwitAsWell: checkSegwitAsWell,
            #maxUnusedAddressGap: maxUnusedAddressGap,
            #maxNumberOfIndexesToCheck: maxNumberOfIndexesToCheck,
          },
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
  @override
  _i16.Future<_i12.Address> getMyNotificationAddress() => (super.noSuchMethod(
        Invocation.method(
          #getMyNotificationAddress,
          [],
        ),
        returnValue: _i16.Future<_i12.Address>.value(_FakeAddress_11(
          this,
          Invocation.method(
            #getMyNotificationAddress,
            [],
          ),
        )),
      ) as _i16.Future<_i12.Address>);
  @override
  _i16.Future<List<String>> lookupKey(String? paymentCodeString) =>
      (super.noSuchMethod(
        Invocation.method(
          #lookupKey,
          [paymentCodeString],
        ),
        returnValue: _i16.Future<List<String>>.value(<String>[]),
      ) as _i16.Future<List<String>>);
  @override
  _i16.Future<String?> paymentCodeStringByKey(String? key) =>
      (super.noSuchMethod(
        Invocation.method(
          #paymentCodeStringByKey,
          [key],
        ),
        returnValue: _i16.Future<String?>.value(),
      ) as _i16.Future<String?>);
  @override
  _i16.Future<String> storeCode(String? paymentCodeString) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeCode,
          [paymentCodeString],
        ),
        returnValue: _i16.Future<String>.value(''),
      ) as _i16.Future<String>);
  @override
  void initCoinControlInterface({
    required String? walletId,
    required String? walletName,
    required _i17.Coin? coin,
    required _i7.MainDB? db,
    required _i16.Future<int> Function()? getChainHeight,
    required _i16.Future<void> Function(_i6.Balance)? refreshedBalanceCallback,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #initCoinControlInterface,
          [],
          {
            #walletId: walletId,
            #walletName: walletName,
            #coin: coin,
            #db: db,
            #getChainHeight: getChainHeight,
            #refreshedBalanceCallback: refreshedBalanceCallback,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i16.Future<void> refreshBalance({bool? notify = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshBalance,
          [],
          {#notify: notify},
        ),
        returnValue: _i16.Future<void>.value(),
        returnValueForMissingStub: _i16.Future<void>.value(),
      ) as _i16.Future<void>);
}

/// A class which mocks [ElectrumX].
///
/// See the documentation for Mockito's code generation for more information.
class MockElectrumX extends _i1.Mock implements _i4.ElectrumX {
  MockElectrumX() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set failovers(List<_i4.ElectrumXNode>? _failovers) => super.noSuchMethod(
        Invocation.setter(
          #failovers,
          _failovers,
        ),
        returnValueForMissingStub: null,
      );
  @override
  int get currentFailoverIndex => (super.noSuchMethod(
        Invocation.getter(#currentFailoverIndex),
        returnValue: 0,
      ) as int);
  @override
  set currentFailoverIndex(int? _currentFailoverIndex) => super.noSuchMethod(
        Invocation.setter(
          #currentFailoverIndex,
          _currentFailoverIndex,
        ),
        returnValueForMissingStub: null,
      );
  @override
  String get host => (super.noSuchMethod(
        Invocation.getter(#host),
        returnValue: '',
      ) as String);
  @override
  int get port => (super.noSuchMethod(
        Invocation.getter(#port),
        returnValue: 0,
      ) as int);
  @override
  bool get useSSL => (super.noSuchMethod(
        Invocation.getter(#useSSL),
        returnValue: false,
      ) as bool);
  @override
  _i16.Future<dynamic> request({
    required String? command,
    List<dynamic>? args = const [],
    Duration? connectionTimeout = const Duration(seconds: 60),
    String? requestID,
    int? retries = 2,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [],
          {
            #command: command,
            #args: args,
            #connectionTimeout: connectionTimeout,
            #requestID: requestID,
            #retries: retries,
          },
        ),
        returnValue: _i16.Future<dynamic>.value(),
      ) as _i16.Future<dynamic>);
  @override
  _i16.Future<List<Map<String, dynamic>>> batchRequest({
    required String? command,
    required Map<String, List<dynamic>>? args,
    Duration? connectionTimeout = const Duration(seconds: 60),
    int? retries = 2,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchRequest,
          [],
          {
            #command: command,
            #args: args,
            #connectionTimeout: connectionTimeout,
            #retries: retries,
          },
        ),
        returnValue: _i16.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i16.Future<List<Map<String, dynamic>>>);
  @override
  _i16.Future<bool> ping({
    String? requestID,
    int? retryCount = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #ping,
          [],
          {
            #requestID: requestID,
            #retryCount: retryCount,
          },
        ),
        returnValue: _i16.Future<bool>.value(false),
      ) as _i16.Future<bool>);
  @override
  _i16.Future<Map<String, dynamic>> getBlockHeadTip({String? requestID}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBlockHeadTip,
          [],
          {#requestID: requestID},
        ),
        returnValue:
            _i16.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i16.Future<Map<String, dynamic>>);
  @override
  _i16.Future<Map<String, dynamic>> getServerFeatures({String? requestID}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getServerFeatures,
          [],
          {#requestID: requestID},
        ),
        returnValue:
            _i16.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i16.Future<Map<String, dynamic>>);
  @override
  _i16.Future<String> broadcastTransaction({
    required String? rawTx,
    String? requestID,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #broadcastTransaction,
          [],
          {
            #rawTx: rawTx,
            #requestID: requestID,
          },
        ),
        returnValue: _i16.Future<String>.value(''),
      ) as _i16.Future<String>);
  @override
  _i16.Future<Map<String, dynamic>> getBalance({
    required String? scripthash,
    String? requestID,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBalance,
          [],
          {
            #scripthash: scripthash,
            #requestID: requestID,
          },
        ),
        returnValue:
            _i16.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i16.Future<Map<String, dynamic>>);
  @override
  _i16.Future<List<Map<String, dynamic>>> getHistory({
    required String? scripthash,
    String? requestID,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHistory,
          [],
          {
            #scripthash: scripthash,
            #requestID: requestID,
          },
        ),
        returnValue: _i16.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i16.Future<List<Map<String, dynamic>>>);
  @override
  _i16.Future<Map<String, List<Map<String, dynamic>>>> getBatchHistory(
          {required Map<String, List<dynamic>>? args}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBatchHistory,
          [],
          {#args: args},
        ),
        returnValue: _i16.Future<Map<String, List<Map<String, dynamic>>>>.value(
            <String, List<Map<String, dynamic>>>{}),
      ) as _i16.Future<Map<String, List<Map<String, dynamic>>>>);
  @override
  _i16.Future<List<Map<String, dynamic>>> getUTXOs({
    required String? scripthash,
    String? requestID,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUTXOs,
          [],
          {
            #scripthash: scripthash,
            #requestID: requestID,
          },
        ),
        returnValue: _i16.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i16.Future<List<Map<String, dynamic>>>);
  @override
  _i16.Future<Map<String, List<Map<String, dynamic>>>> getBatchUTXOs(
          {required Map<String, List<dynamic>>? args}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBatchUTXOs,
          [],
          {#args: args},
        ),
        returnValue: _i16.Future<Map<String, List<Map<String, dynamic>>>>.value(
            <String, List<Map<String, dynamic>>>{}),
      ) as _i16.Future<Map<String, List<Map<String, dynamic>>>>);
  @override
  _i16.Future<Map<String, dynamic>> getTransaction({
    required String? txHash,
    bool? verbose = true,
    String? requestID,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransaction,
          [],
          {
            #txHash: txHash,
            #verbose: verbose,
            #requestID: requestID,
          },
        ),
        returnValue:
            _i16.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i16.Future<Map<String, dynamic>>);
  @override
  _i16.Future<Map<String, dynamic>> getAnonymitySet({
    String? groupId = r'1',
    String? blockhash = r'',
    String? requestID,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAnonymitySet,
          [],
          {
            #groupId: groupId,
            #blockhash: blockhash,
            #requestID: requestID,
          },
        ),
        returnValue:
            _i16.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i16.Future<Map<String, dynamic>>);
  @override
  _i16.Future<dynamic> getMintData({
    dynamic mints,
    String? requestID,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMintData,
          [],
          {
            #mints: mints,
            #requestID: requestID,
          },
        ),
        returnValue: _i16.Future<dynamic>.value(),
      ) as _i16.Future<dynamic>);
  @override
  _i16.Future<Map<String, dynamic>> getUsedCoinSerials({
    String? requestID,
    required int? startNumber,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUsedCoinSerials,
          [],
          {
            #requestID: requestID,
            #startNumber: startNumber,
          },
        ),
        returnValue:
            _i16.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i16.Future<Map<String, dynamic>>);
  @override
  _i16.Future<int> getLatestCoinId({String? requestID}) => (super.noSuchMethod(
        Invocation.method(
          #getLatestCoinId,
          [],
          {#requestID: requestID},
        ),
        returnValue: _i16.Future<int>.value(0),
      ) as _i16.Future<int>);
  @override
  _i16.Future<Map<String, dynamic>> getFeeRate({String? requestID}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFeeRate,
          [],
          {#requestID: requestID},
        ),
        returnValue:
            _i16.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i16.Future<Map<String, dynamic>>);
  @override
  _i16.Future<_i14.Decimal> estimateFee({
    String? requestID,
    required int? blocks,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #estimateFee,
          [],
          {
            #requestID: requestID,
            #blocks: blocks,
          },
        ),
        returnValue: _i16.Future<_i14.Decimal>.value(_FakeDecimal_13(
          this,
          Invocation.method(
            #estimateFee,
            [],
            {
              #requestID: requestID,
              #blocks: blocks,
            },
          ),
        )),
      ) as _i16.Future<_i14.Decimal>);
  @override
  _i16.Future<_i14.Decimal> relayFee({String? requestID}) =>
      (super.noSuchMethod(
        Invocation.method(
          #relayFee,
          [],
          {#requestID: requestID},
        ),
        returnValue: _i16.Future<_i14.Decimal>.value(_FakeDecimal_13(
          this,
          Invocation.method(
            #relayFee,
            [],
            {#requestID: requestID},
          ),
        )),
      ) as _i16.Future<_i14.Decimal>);
}
